### ISSUE TITLE
This doesn't work with angular 2 

### ISSUE THREAD

**Issue by uttamsingh** [deepu105/generator-jhipster-bootswatch#11]
Fails with below error

Unable to find src/main/webapp/app/blocks/config/http.config.js or missing required jhipster-needle. Interceptor not added to JHipster app.

Unable to find src/main/webapp//index.html or missing required needle. File rewrite failed.

identical src/main/webapp/app/components/bootswatch/bootswatch.service.js
identical src/main/webapp/app/components/bootswatch/bootswatch.directive.js
identical src/main/webapp/app/components/bootswatch/bootswatch.controller.js
identical src/main/webapp/app/components/interceptor/bootswatch.interceptor.js
identical src/main/webapp/i18n/en/global.json
identical src/main/webapp/i18n/hi/global.json
identical src/main/webapp/index.html

Running gulp Inject to add javascript to index

events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn gulp ENOENT
    at exports._errnoException (util.js:1016:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

**Comment by deepu105** [comment]
It doesn't support Angular2. PR welcome
