### ISSUE TITLE
Unable to find src/main/webapp/app/blocks/config/http.config.js or missing required jhipster-needle. Interceptor not added to JHipster app.

### ISSUE THREAD

**Issue by TomYule** [deepu105/generator-jhipster-bootswatch#14]
Unable to find src/main/webapp/app/blocks/config/http.config.js or missing required jhipster-needle. Interceptor not added to JHipster app.

yo jhipster-bootswatch

**Comment by deepu105** [comment]
This only works with JHipster 4 with AngularJS. There is no support for Angular or React yet. If someone is willing to contribute that you are welcome.

**Comment by deepu105** [comment]
see https://github.com/hipster-labs/generator-jhipster-bootswatch/issues/10
